apiVersion: v2
name: astrid
description: Astrid — fitness and nutrition tracker
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: postgresql
    version: "16.4.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "20.6.2"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
  - name: replicated
    repository: oci://registry.replicated.com/library
    version: "1.19.0"
    condition: replicated.enabled
