image:
  repository: images.astrid.fit/proxy/astrid/docker.io/alicenstar/astrid
  tag: "latest"
  pullPolicy: Always

service:
  type: NodePort

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: tender-ride.ingress.replicatedcluster.com
      paths:
        - path: /
          pathType: Prefix
    - host: app.astrid.fit
      paths:
        - path: /
          pathType: Prefix

tls:
  mode: selfsigned
