{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "astrid.fullname" . }}
  labels:
    {{- include "astrid.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if eq .Values.tls.mode "auto" }}
  annotations:
    cert-manager.io/{{ .Values.tls.certManager.issuerKind | lower }}: {{ .Values.tls.certManager.issuerName }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if or (eq .Values.tls.mode "auto") (eq .Values.tls.mode "manual") (eq .Values.tls.mode "selfsigned") }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      {{- if eq .Values.tls.mode "manual" }}
      secretName: {{ .Values.tls.secretName }}
      {{- else }}
      secretName: {{ include "astrid.fullname" . }}-tls
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "astrid.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
